// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application";
import NabarController from "./navbar_controller";
import RosterController from "./roster_controller";
import DropdownController from "./dropdown_controller";
import StickyHeroController from "./sticky_hero_controller";

application.register("navbar", NabarController);
application.register("roster", RosterController);
application.register("dropdown", DropdownController);
application.register("sticky", StickyHeroController);
